#!/bin/bash
echo "=== GitHub Secrets Setup Guide ==="
echo ""
echo "To set up your GitHub repository for CI/CD, follow these steps:"
echo ""
echo "1. Go to your repository: https://github.com/syedwahid/student-app-simple-k8s-GitActions"
echo ""
echo "2. Click on 'Settings' > 'Secrets and variables' > 'Actions'"
echo ""
echo "3. Add the following secrets:"
echo ""
echo "   GCP_PROJECT_ID:"
echo "     - Your GCP Project ID (e.g., 'my-project-123456')"
echo ""
echo "   GCP_CREDENTIALS:"
echo "     - Create a service account in GCP with 'Compute Admin' role"
echo "     - Download the JSON key file"
echo "     - Copy the ENTIRE JSON content"
echo "     - Paste it as the secret value"
echo ""
echo "   DOCKER_USERNAME:"
echo "     - Your Docker Hub username"
echo ""
echo "   DOCKER_TOKEN:"
echo "     - Go to Docker Hub > Account Settings > Security"
echo "     - Generate an access token"
echo "     - Use that token as the secret"
echo ""
echo "4. Save all secrets"
echo ""
echo "5. Push your code to trigger the workflow:"
echo "   git add ."
echo "   git commit -m 'Setup CI/CD pipeline'"
echo "   git push origin main"
echo ""
echo "The workflow will automatically:"
echo "1. Run tests"
echo "2. Build Docker image"
echo "3. Create GCP VM with Terraform"
echo "4. Deploy application to VM"
echo ""
echo "Check progress in: Actions → Workflows"